export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          role: string;
          status: string;
          plan: string;
          stripe_customer_id: string | null;
          subscription_id: string | null;
          subscription_status: string | null;
          daily_outfit_limit: number;
          outfits_used_today: number;
          ai_scan_limit: number;
          ai_scans_used_today: number;
          scan_count: number;
          scan_limit: number;
          last_scan_reset: string;
          last_reset_date: string;
          last_sign_in_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: string;
          status?: string;
          plan?: string;
          stripe_customer_id?: string | null;
          subscription_id?: string | null;
          subscription_status?: string | null;
          daily_outfit_limit?: number;
          outfits_used_today?: number;
          ai_scan_limit?: number;
          ai_scans_used_today?: number;
          scan_count?: number;
          scan_limit?: number;
          last_scan_reset?: string;
          last_reset_date?: string;
          last_sign_in_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: string;
          status?: string;
          plan?: string;
          stripe_customer_id?: string | null;
          subscription_id?: string | null;
          subscription_status?: string | null;
          daily_outfit_limit?: number;
          outfits_used_today?: number;
          ai_scan_limit?: number;
          ai_scans_used_today?: number;
          scan_count?: number;
          scan_limit?: number;
          last_scan_reset?: string;
          last_reset_date?: string;
          last_sign_in_at?: string | null;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          email: string | null;
          display_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email?: string | null;
          display_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          email?: string | null;
          display_name?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
      wardrobe_items: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          category: string;
          color: string | null;
          subcategory: string | null;
          brand: string | null;
          size_label: string | null;
          colors: string[];
          season_tags: string[];
          occasion_tags: string[];
          material_tags: string[];
          image_url: string;
          cloudinary_public_id: string | null;
          visibility: string;
          purchase_url: string | null;
          purchase_price: number | null;
          currency: string | null;
          last_worn_at: string | null;
          wear_count: number;
          ai_attributes: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          category: string;
          color?: string | null;
          subcategory?: string | null;
          brand?: string | null;
          size_label?: string | null;
          colors?: string[];
          season_tags?: string[];
          occasion_tags?: string[];
          material_tags?: string[];
          image_url: string;
          cloudinary_public_id?: string | null;
          visibility?: string;
          purchase_url?: string | null;
          purchase_price?: number | null;
          currency?: string | null;
          last_worn_at?: string | null;
          wear_count?: number;
          ai_attributes?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          name?: string;
          category?: string;
          color?: string | null;
          subcategory?: string | null;
          brand?: string | null;
          size_label?: string | null;
          colors?: string[];
          season_tags?: string[];
          occasion_tags?: string[];
          material_tags?: string[];
          image_url?: string;
          cloudinary_public_id?: string | null;
          visibility?: string;
          purchase_url?: string | null;
          purchase_price?: number | null;
          currency?: string | null;
          last_worn_at?: string | null;
          wear_count?: number;
          ai_attributes?: Json;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      outfit_recommendations: {
        Row: {
          id: string;
          user_id: string;
          request_hash: string | null;
          occasion: string | null;
          season: string | null;
          weather_context: Json;
          destination: string | null;
          prompt: string | null;
          item_ids: string[];
          response: Json;
          score: number | null;
          model_name: string | null;
          status: string;
          generated_at: string;
          expires_at: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          request_hash?: string | null;
          occasion?: string | null;
          season?: string | null;
          weather_context?: Json;
          destination?: string | null;
          prompt?: string | null;
          item_ids?: string[];
          response?: Json;
          score?: number | null;
          model_name?: string | null;
          status?: string;
          generated_at?: string;
          expires_at?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          request_hash?: string | null;
          occasion?: string | null;
          season?: string | null;
          weather_context?: Json;
          destination?: string | null;
          prompt?: string | null;
          item_ids?: string[];
          response?: Json;
          score?: number | null;
          model_name?: string | null;
          status?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      usage_limits: {
        Row: {
          id: string;
          user_id: string;
          period_start: string;
          period_end: string;
          recommendations_used: number;
          recommendations_limit: number;
          uploads_used: number;
          uploads_limit: number;
          storage_bytes_used: number;
          storage_bytes_limit: number;
          metadata: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          period_start: string;
          period_end: string;
          recommendations_used?: number;
          recommendations_limit?: number;
          uploads_used?: number;
          uploads_limit?: number;
          storage_bytes_used?: number;
          storage_bytes_limit?: number;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          recommendations_used?: number;
          recommendations_limit?: number;
          uploads_used?: number;
          uploads_limit?: number;
          storage_bytes_used?: number;
          storage_bytes_limit?: number;
          metadata?: Json;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      activity_logs: {
        Row: {
          id: string;
          user_id: string | null;
          event_type: string;
          entity_type: string | null;
          entity_id: string | null;
          ip_address: string | null;
          user_agent: string | null;
          metadata: Json;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          event_type: string;
          entity_type?: string | null;
          entity_id?: string | null;
          ip_address?: string | null;
          user_agent?: string | null;
          metadata?: Json;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          metadata?: Json;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      feature_flags: {
        Row: {
          id: boolean;
          ai_scan_enabled: boolean;
          outfit_generator_enabled: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: boolean;
          ai_scan_enabled?: boolean;
          outfit_generator_enabled?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          ai_scan_enabled?: boolean;
          outfit_generator_enabled?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      revenue_placeholder: {
        Row: {
          id: string;
          user_id: string;
          plan: string;
          start_date: string;
          status: string;
          stripe_customer_id: string | null;
          stripe_subscription_id: string | null;
          stripe_checkout_session_id: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          plan: string;
          start_date?: string;
          status?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_checkout_session_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          plan?: string;
          start_date?: string;
          status?: string;
          stripe_customer_id?: string | null;
          stripe_subscription_id?: string | null;
          stripe_checkout_session_id?: string | null;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
